#!/bin/sh
# When configured within MPICH via PAC_CONFIG_SUBDIR, this file will be sourced
# by the top-level configure.  This lets us propagate shell variable changes
# back upstream.

CPPFLAGS="  -I/home/timndus/msc_project/mpich/tmp/src/mpl/include -I/home/timndus/msc_project/mpich/mpich-3.2.1/src/mpl/include -I/home/timndus/msc_project/mpich/mpich-3.2.1/src/openpa/src -I/home/timndus/msc_project/mpich/tmp/src/openpa/src -D_REENTRANT -I/home/timndus/msc_project/mpich/tmp/src/mpi/romio/include"
WRAPPER_LIBS="$WRAPPER_LIBS "
